<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Subhadip" failures="1" tests="1" name="Test" time="6.299" errors="0" timestamp="2024-12-23T12:58:03 IST">
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
at utilities.DataProviders.getData(DataProviders.java:21)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validate_login -->
</testsuite> <!-- Test -->
